### ISSUE TITLE
Dicussion: Simplifying UYIR MEI MATCH feedback mechanism in the UI

### ISSUE THREAD

**Issue by tecoholic** [psankar/tamil-wordle#7]
Opening this issue to discuss the UYIR MEI Match algorithm as Twitter thread are getting wild and difficult to follow.

### Proposal

I will start with my proposal of expanding the results from YES(Green) / NO(Gray) / MISPOSITIONED (Yellow) match to include PARTIAL (UYIR/MEI) (Green Gradient) as below:

![matches](https://user-images.githubusercontent.com/383862/149912740-8f764270-a2df-422f-b89e-2f026d4b5590.png)

Initially I wanted to focus only on the "MEI" and use a different color like Blue. However based on the suggestions[1] made by Jean-Luc Chevillard, I think it makes sense to keep a partial fill of the box to indicate either a UYIR or MEI match.

## Current Implementation and comparison

Considering @psankar's experimental UI as the current implementation of UYIR/MEI match where 2 dimensions are considered using a combination of 2 emojis, here are the differences:

1. The API response if maintained as an 1 dimensional array. Frankly, I don't understand cases like ["LETTER_ELSEWHERE", "MEI_MATCHED"]. While I understand the API response to mean that the letter in the box is an exact match elsewhere and the MEI used in the box is also a partial match in the current location, I don't see how to represent this in the UI and also as a player, I don't understand it at all. It took me a solid day to wrap this 2-dimensional feedback around in my head. I don't feel like it will make the game easier or more intuitive to play.
2. We can consider a partial-mispositioned letter response for feedback like the one below as well. But it increases the complexity of the feedback and I am personally don't think it would make the game easier and more fun.
![matches-2](https://user-images.githubusercontent.com/383862/149915777-c59bbd38-7491-4b29-8257-9cf5ab92c733.png)

Kindly post your thoughts. I am attaching a JS implementation of the checker I wrote for testing the above proposal as a comment below.

[1] - [Twitter thread](https://twitter.com/JLC1956/status/1483014818663698433?s=20)

**Comment by tecoholic** [comment]
```js
const diacritics = {
  "\u0B82": true,
  "\u0BBE": true,
  "\u0BBF": true,
  "\u0BC0": true,
  "\u0BC1": true,
  "\u0BC2": true,
  "\u0BC6": true,
  "\u0BC7": true,
  "\u0BC8": true,
  "\u0BCA": true,
  "\u0BCB": true,
  "\u0BCC": true,
  "\u0BCD": true,
  "\u0BD7": true,
};

const vowels = {
  "\u0B85": true,
  "\u0B86": true,
  "\u0B87": true,
  "\u0B88": true,
  "\u0B89": true,
  "\u0B8A": true,
  "\u0B8E": true,
  "\u0B8F": true,
  "\u0B90": true,
  "\u0B92": true,
  "\u0B93": true,
  "\u0B94": true,
};

/**
 * Convert a string into an array of strings representing Tamil letters
 *
 * @param {string} word String containing the word to convert to letters
 * @returns an Array of strings that is equivalent to letters in Tamil
 */
function toTamilLetters(word) {
  let letters = [];
  for (let i = 0; i !== word.length; i++) {
    let ch = word[i];
    diacritics[ch] && letters.length && letters[letters.length - 1].length < 2
      ? (letters[letters.length - 1] += ch)
      : letters.push(ch);
  }
  return letters;
}

/**
 * Verify that the letters match the letters of today's word
 **/

function verify (letters) {
  let word = "உதயசூரியன்";  // dummy word to test against
  let REF = toTamilLetters(word);
  let results = Array(letters.length).fill("LETTER_NOT_FOUND");

  for (let i = 0; i < letters.length; i++) {
    // letter exists in the exact position
    console.log("processing: ", letters[i]);

    if (REF[i] === letters[i]) {
      results[i] = "FOUND";
      console.log("FOUND");
      continue;
    }
    if (REF.indexOf(letters[i]) !== -1) {
      results = "OTHER POSITION";
      console.log("OTHER POSITION");
      continue;
    }

    // MEI match
    let mei = letters[i][0];
    if (vowels[mei]) {
      console.log("Vowel found");
      continue;
    } else {
      if (REF[i].includes(mei)) {
        console.log("MEI MATCH");
        results[i] = "MEI MATCH";
        continue;
      }
    }

    if (letters[i].length === 2) {
      let kombu = letters[i][1];
      if (REF[i].includes(kombu)) {
        console.log("UYIR MATCH");
        results[i] = "UYIR MATCH";
      }
    }
    console.log("INVALID");
  }
  return results;
};

export default verify;
```

**Comment by tecoholic** [comment]
@tsureshkumar Hi, adding you to this discussion as well.

**Comment by varunkumar** [comment]
I could think of two options here:

1. You can migrate to the new API (which returns 2D array) but for cases `[LetterNotFound, Uyir|MeiMatched]` and `[LetterElseWhere, Uyir|MeiMatched]`, you can choose to skip the `LetterNotFound` & `LetterElseWhere`. Half shaded green in the proposal looks good in that way. The only thing is that with this representation, we are losing out on an additional information if the letter is present elsewhere or not found at all. 

2. Retain the colors the way they are. Grey (`LetterNotFound`), Amber (`LetterElseWhere`), Green (`LetterMatched`). We can adopt a different shape for UYIR (circle) and MEI (triangle) match. So, color will continue to indicate only the position. Additionally, shape of the letter can give an indication on UYIR or MEI match. 

Personally, I would prefer option#2. But, we need to see it in action to decide how easy / complex that becomes for the user.

**Comment by tsureshkumar** [comment]
Sorry, I missed this discussion earlier.

While I find this feature complex and constricted, some people find it useful when they feel the word is difficult.

This match is a two dimensional information (positional hint and letter hint).  This can't  be represented in one UI signal alone.  You need two signals (Color, shape)  or supplementary icon.  Otherwise, flatten and have 6 emojis.

I took a simple approach with horizontal bars and vertical bars.  Along with the earlier letter hints, at each position I introduced green bars.  In my view, uyir match and mei match just follow the Tamiil letters matrix we learn in school.   Horizontal lines - follow left or right in the same row,  for example த தா தி து…. Vertical lines follow up or down in the same column கி ஙி சி ஞி… This,I feel, is intuitive.


![Screenshot from 2022-01-21 01-52-59](https://user-images.githubusercontent.com/108256/150416264-5e6ae2ab-b977-4267-b029-0b1cd993031e.png)

![2](https://user-images.githubusercontent.com/108256/150417778-6d168b3c-7e0a-47de-81b0-f5cf13c36808.png)

**Comment by tecoholic** [comment]
I think the above makes a lot of UI sense. Thanks everyone for the inputs. Closing the discussion for now. :)
